spring:
  profiles:
    active: cloud
---
spring:
  application:
    name: ${vcap.application.name}
  cloud:
    services:
      registrationMethod: route

---
spring:
  profiles: cloud
  jpa:
    show_sql: false
    database: mysql
    hibernate:
      ddl-auto: none

security:
  basic:
    enabled: false