spring:
  profiles:
    active: cloud
---

spring:
  profiles: cloud
  spring:
    application:
      name: ${vcap.application.name}
    cloud:
      services:
        registrationMethod: route

jpa:
  show_sql: false
  database: mysql
  hibernate:
    ddl-auto: none

ribbon:
  eureka:
    enabled: true

security:
  basic:
    enabled: false

---
spring:
  profile: prod

  security:
    basic:
      enabled: true